version: "3"

services:
  mariadb:
    container_name: "mariadb"
    build: ./requirements/mariadb
    volumes: 
      - ${HOME}/mariadb:/var/www/mysql
    restart: always
    ports:
      - "3306:3306"
    networks: 
      - localhots
    env_file:
      - .env

  nginx:
    container_name: "nginx"
    build: ./requirements/nginx
    volumes: 
      - ${HOME}/data/website:/var/www/html
    depends_on:
      - wordpress
    ports: 
      - "443:443"
    restart: always
    networks: 
      - localhots
    env_file:
      - .env
    depends_on: 
      - mariadb


  wordpress:
    container_name: "wordpress"
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    volumes: 
      - ${HOME}/data/website:/var/www/html
    restart: always
    ports: 
      - "9000:9000"
    networks: 
      - localhots
    env_file:
      - .env

networks:
  localhots:
    name: inception

volumes:
  db-data:
    driver_opts:
      type: none
      device: /home/dbalducc/data/db-data
      o: bind
  www-data:
    driver_opts:
      type: none
      device: /home/dbalducc/data/www-data
      o: bind